# fly.toml app configuration file generated for tylerharpool-blog on 2025-04-28T15:24:17-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tylerharpool'
primary_region = 'dfw'

[build]
  # builder = "heroku/buildpacks:20"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  kill_signal = "SIGINT"
  kill_timeout = "5s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
